services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports: 
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./data:/home/node/.n8n
      - ./files:/files
    networks:
      - n8n_network

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./n8n.yaml:/etc/ngrok.yml:ro
    ports:
      - "4040:4040"  # ngrok dashboard
    environment:
      - NGROK_AUTHTOKEN=${N8N_AUTHTOKEN}
    networks:
      - n8n_network
    depends_on:
      - n8n

  python-app:
    build: .
    restart: always
    ports: 
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./files:/app/files
    networks:
      - n8n_network

networks:
  n8n_network:
    name: n8n_network


